language: node_js
node_js:
- stable
cache:
  directories:
  - node_modules
script:
- npm run build
deploy:
  provider: firebase
  token:
    secure: y8kEcK4Z4xQGym+rlvbCC/d5KXS8gfEelUWgdDvMxIqesEXjMyB9yPnP7VyZaolAxk9VnwVsgCm4XGiuIEOIvIRVy+RqRvgdp5vR40F/wkV4xQY5Xeufzi14xSDsmSLHBvxoFZGa/LskCH+6w/HtApanOqs8qS6AREmBhZSMBCYhyJ1FLRLxMazJG93nd3WRWrkkuicBfZqqph7T54zK2Htqt38c9lvBs2GRiJYspcUZwbr3bkRcEOr//Uh05fgLUrWVQbK0hFe7zDh2ZQsMJNUIaHOJh0WjN784UR7GNavwjTXHE4s3fjfoyDE+OL1FKHa4yHi2GKM6icQoRWmTqsb9s8tDVNDKkLw0dOCxwLJ/c7Kzj3q1aZ1L8LafT1pmVHmSoOxw5uMFWfSDrXPwkOJTRXYy5xjh88gNIuVPWCNQttHAos1mmEOLgnWzWiVK7MUe/6vlQSQo9W3gLvvwIsgA5vFhoxK3KCceY+Fd/nHWVR6DCk4w9z8M27IeIKR9Y+wl4ZOM7KYT3fuYGUQGQtVNO6C5/4L1yOxev7B8ncVpTF50kMARcxvLC79wv2wpgXagWKLfE532moEMZ/givv8lm6MUOL+m3jLcdTtrw90167tC+oTOFo/sRNcFuCBpbclQBMh9NH+LZgQ5BlyUKEkWJUsIYrnZSSA8YvQJdPU=
  project: angomi-9e9af
  on:
    branch: master
env:
  global:
    secure: FpT9j2KyfMPVKvj7/fGCffC2kacceWdH5FyTzojpi7ptR0Z+5Nz0kd4bG0OJlZMrpRNtzmj3j+vz9s4KOYdR7QlmzffCu7EBTHJ+wf48g5VSLtUAGwCFmFInyuo7uOEosNR2iG56Q+jF/SqQ2kP394CLM03XxHkTResEboCpN/Giq8LaHkcrb7ZoWVsPdZtPUREMt+8Ntk5jCvzZ8TDTn2N6BR8hvN8ywmGxGrNJry3etst3MxcEDSrS2Ih9y8Xgw2aIOlIfwZ2gBAoMcvRcnPIe9vNVFso+EQMeSRh9aCJVnPz6KV5u6coXSydN+QCXOOUUr0VR8GHtgFZq0sjTXEZ5ltEKVKS0YoxuI6KCPytykNp6g+OfXe7qwGVqjBGBbxITyPnbnJYPLx+nrXnliDsWpt1GgoBaXM+j76VKrmyW5nD+X7aoukGVfUpoOOrg2SchdoqqP29pKRM4Eid3dvTGiDX29QVRETuYHihmMSw1Txk1acspBisacQ96TVoS8qrVU4Ivd8JaYcJrwkOXqWNpyOcIZbiIli1OBFs1rtKzMEN3tC9zXQV3fdGcfCe5ZKAXV/24Q0kAP6BUz3qJYwlUpLqm43OyYYlUMuLgfvGWp1fJ7AE6l6ssc7FICUKCl9wrrWCZXlhIpQO2i5YXJD0MPYZtNi8TwzskxaJeuc0=
